import { Component, input, viewChild, effect, inject, EnvironmentInjector } from '@angular/core';
import { DOCUMENT } from '@angular/common';

/**
 * Standalone Angular component for displaying rendered DOCX content.
 *
 * Receives pre-rendered HTML from the DocxRenderer service (generated by the docx-preview library)
 * and displays it in a scrollable container with proper styling.
 *
 * Uses Angular effects to reactively update the DOM when input content changes.
 * Handles both successful preview content and error states.
 *
 * Note: The actual DOCX rendering is done by the docx-preview library in the renderer service.
 * This component just displays the already-rendered HTML.
 */
@Component({
  selector: 'mad-docx-preview',
  standalone: true,
  templateUrl: './docx-preview.component.html',
  styleUrls: ['./docx-preview.component.scss'],
})
export class DocxPreviewComponent {
  /**
   * The pre-rendered HTML content of the DOCX document.
   * Generated by the docx-preview library in DocxRenderer and passed to this component.
   * Default: empty string
   */
  readonly docxHtmlContent = input<string>('');

  /**
   * Error flag indicating whether DOCX rendering failed.
   * When true, displays an error message instead of content.
   * Default: false
   */
  readonly isError = input(false);

  private readonly doc = inject(DOCUMENT, { optional: true });
  private readonly hostRef = viewChild<{ nativeElement: HTMLElement }>('docxHost');

  /**
   * Constructor with reactive effect for DOM updates.
   *
   * Sets up an Angular effect that:
   * 1. Watches the docxHtmlContent and isError inputs
   * 2. Clears the host element
   * 3. Either renders error message or HTML content based on isError flag
   * 4. Updates reactively when inputs change
   */
  constructor() {
    effect(
      () => {
        const host = this.hostRef()?.nativeElement;
        if (!host || !this.doc) {
          return;
        }

        const content = this.docxHtmlContent();
        const isErr = this.isError();

        host.innerHTML = '';

        if (isErr) {
          const errorDiv = this.doc.createElement('div');
          errorDiv.className = 'docx-placeholder';
          errorDiv.textContent = 'Unable to render DOCX preview';
          host.appendChild(errorDiv);
        } else if (content) {
          const container = this.doc.createElement('div');
          container.className = 'docx-preview-document';
          container.innerHTML = content;
          host.appendChild(container);
        }
      },
      { allowSignalWrites: true },
    );
  }
}
